import type { Metadata } from "next";
import "./globals.css";
import RootLayoutClient from "./RootLayoutClient";
import Header from "@/components/custom/Header";
import { ConvexClientProvider } from "./ConvexClientProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/custom/AppSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen flex flex-col">
        <ConvexClientProvider>
          <RootLayoutClient>
            {/* Header remains at the top */}
            <Header />
            {/* Sidebar and main content */}
            <div className="flex flex-grow">
              <SidebarProvider defaultOpen={false}>
                <div className="flex flex-row w-full">
                  <AppSidebar className="flex-shrink-0 w-64 bg-purple-500" />
                  <main className="flex-grow flex flex-col items-center justify-start">
                    {children}
                  </main>
                </div>
              </SidebarProvider>
            </div>
          </RootLayoutClient>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
